### ISSUE TITLE
ModuleNotFoundError: No module named 'pytz'

### ISSUE THREAD

**Issue by MADECICCO** [wmpg/WesternMeteorPyLib#1]
Hi!

After following instructions, I tried this test: 
python -m wmpl.Trajectory.Trajectory

And finished with error:
ModuleNotFoundError: No module named 'pytz'

**Comment by MADECICCO** [comment]
I solved it doing , underr wpml enviroment, : 

conda install -y -c conda forge pytz

**Comment by dvida** [comment]
Huh, it's interesting that it did not get installed automatically with other packages. I added it to the list now, thanks!
