### ISSUE TITLE
Incorrect return  from estimateTimingAndVelocity if estimate_timing_vel is false

### ISSUE THREAD

**Issue by markmac99** [wmpg/WesternMeteorPyLib#5]
If estimate_timing_vel is false, then this function returns two values at line 2878 
However, the signature of this function expects it to return five parameters. (success, vel_fit, v_init, time_diffs, observations)

This causes Trajectory().run() to fail at line 5528 if estimate_timing_vel is set to false. 

Additionally saveReport() will fail at line 3697, as if timing_res and timing_stddev are not set if estimate_timing_vel is false. 

I've worked around this but as i do not know what should be returned if timing estimates are not required, i've had to guess!
        if not estimate_timing_vel:
            return True, np.zeros(2), v_init, time_diffs, observations

and later on just test if estimate_timing_vel is true before printing the timing statistics
        if self.estimate_timing_vel is True:
            out_str += "  Avg. res. = {:.3e} s\n".format(self.timing_res)
            out_str += "  Stddev    = {:.2e} s\n".format(self.timing_stddev)

**Comment by dvida** [comment]
Thanks Mark, I fixed it. Feel free to test it now.

**Comment by markmac99** [comment]
merged in, tested. all seems good - thanks !
